// Application version history. Update this file when releasing new versions.

namespace DatPlotX.Content;

public static class AppChangelogContent
{
    public static ChangelogEntry[] GetEntries() =>
    [
        new("0.14.11", "2 July 2026",
        [
            "Grouped Parameter Plot: zooming in and then toggling markers, the legend, or an input value no longer snaps the view back — your zoom is kept.",
            "Grouped Parameter Plot: hold Ctrl and drag to zoom into a rectangle (matching Stacked panes), with a cross cursor while Ctrl is held. Plain drag still pans; two-finger and axis-edge zoom still work.",
            "Grouped Parameter Plot: right-click \"Reset View\" is renamed \"Set Scale to Default\" to match the other plot modes.",
            "Fixed a bug where selecting a rounded input value (e.g. one shown as \"0.8\") could produce a blank grouped plot.",
            "Fixed grouping for columns of very large numbers (epoch-millisecond timestamps, serial numbers) that previously collapsed into a single line.",
            "Fixed imported CSV columns that start as whole numbers and later turn fractional — those later values are no longer silently dropped.",
            "Clear Pane now removes just the curves, leaving your event lines and annotations in place.",
        ]),
        new("0.14.10", "29 June 2026",
        [
            "Curve analysis is now reached from a single \"Statistics\" menu instead of scattered entries, and the metric picker adds R² and the intercept alongside the slope.",
            "Fixed a memory leak: plot panes are now fully released when a pane is removed during a long editing session.",
            "Privacy: the app no longer writes any of your data values or column names into its diagnostic logs.",
            "Settings and your recent-files list now live in the same per-OS folder as the logs and crash reports, so everything is in one place (on macOS they previously landed in a different folder).",
            "Stability and build-quality cleanups from a pre-open-source code review; no change to how you use the app.",
        ]),
        new("0.14.9", "28 June 2026",
        [
            "Reliability and safety hardening ahead of the open-source release. Opening a corrupt or oversized project (.DPX) file now fails cleanly with a message instead of risking an out-of-memory crash.",
            "Fixed a memory leak: closing plot panes during a long session now fully releases them.",
            "Background dialogs (such as the \"too many curves\" warning and the event-line prompt) can no longer crash the app if they hit an unexpected error — the error is logged instead.",
            "Internal groundwork so a future version can let you cancel a very large data import mid-load.",
        ]),
        new("0.14.8", "28 June 2026",
        [
            "You can now rename a parameter and edit its unit after plotting. The Manage Curve dialog (Stacked Panes and Compact Plot Surface) has Name and Unit fields — handy for imported data where a name or unit reads oddly (e.g. renaming \"GLoad (normal)\" to \"GNormal\" with unit \"G\", or clearing \"Mach (ratio)\"'s unit so the mean label reads \"0.778\" instead of \"0.778 ratio\").",
            "A rename / unit edit now updates everywhere consistently: the legend, the Y-axis title, and the Analysis Results panel — including the row label and all metric columns. Previously the change only reached some places (e.g. the Slope column updated but Min / Max / Mean / Std Dev kept the old unit).",
            "The Source Data table intentionally keeps the original imported column name — it mirrors the file as imported; renames are display-label changes on the plot and analysis.",
            "When creating a New Project, you can now double-click one of the three plot-type cards to pick it and create in one step, instead of selecting then clicking Create.",
        ]),
        new("0.14.7", "27 June 2026",
        [
            "Fixed: the top entry in a plot legend is no longer slightly clipped at the top — the tallest letters (like the top of a \"d\" or \"l\") used to be shaved off by the legend border. Applies to Stacked Panes and Grouped Parameter Plots.",
            "Fixed: on the Compact Plot Surface, a slope trend line that reaches the top of its band now shows its value label instead of having the number clipped away — the line was drawn but its number could go missing.",
            "The Analysis Results panel now sits side-by-side with the Source Data table in the bottom pane, with a draggable splitter between them. Toggling it open expands the bottom pane automatically.",
            "Tidied: in Grouped Parameter Plot mode, menus that had no applicable items are no longer shown.",
        ]),
        new("0.14.6", "22 June 2026",
        [
            "The Grouped Parameter Plot now has an \"Export Image…\" item in its right-click menu, matching the Stacked Panes and Compact surfaces. (Export was already available via Ctrl+E and the File menu — this just adds the missing right-click shortcut.)",
        ]),
        new("0.14.5", "19 June 2026",
        [
            "Fixed: on the Compact Plot Surface, an arrow's text label now rotates to follow the arrow when you drag the arrowhead, and the Above / Below alignment now matches the preview instead of being flipped.",
            "Fixed: right-clicking a text or arrow annotation now shows the Edit and Delete options on the Stacked Panes and Grouped surfaces too — previously they only appeared on the Compact surface.",
            "Fixed: on the Grouped surface, dragging an arrow's end now rotates the arrow (moving just that end) instead of sliding the whole arrow, matching the other plot modes.",
            "Fixed: X-Plane data import auto-detects units and trims padding underscores, and slope readouts show a proper rate (including rate-of-climb for altitude data).",
        ]),
        new("0.14.3", "07 June 2026",
        [
            "The Analysis Results table has a cleaner, more polished look — a framed card with a proper header band, alternating row shading, right-aligned numbers that line up by decimal, and quiet action buttons that only light up on hover.",
            "The Slope column now draws its trend line. Click the ╱ button in any Slope, Mean, Min, or Max cell to overlay that line on the plot. The line is drawn in black so it stands out against its own curve.",
            "Click the ╱ button again to cycle the on-plot label: line only → line plus the value (e.g. \"-0.342\") → line plus name and value (\"Slope -0.342\") → off. Each curve and metric is independent, so you control exactly what's labeled.",
            "Fixed: very small slopes that used to show as \"-0\" now show their real value (e.g. -0.0001).",
            "Fixed: the Slope column's ╱ button is now fully visible at the panel's default width instead of being cut off at the right edge.",
        ]),
        new("0.14.2", "05 June 2026",
        [
            "Min and Max cells in the Analysis Results panel now have a 📍 button next to the ⊕ flash button. Click it to drop an event line right at that point's X — the Add Event Line dialog opens pre-filled so you can name and color it. Handy because min/max points aren't saved with the project, but event lines are, so this pins a found peak or trough permanently. Works in Stacked Panes and Compact Plot Surface mode.",
        ]),
        new("0.14.1", "01 June 2026",
        [
            "Refinement: defining an analysis segment by Shift+dragging the Compact plot now ignores a stray click — you have to actually drag before a segment is created, so an accidental Shift+click no longer drops a zero-width segment. Matches how it already worked in Stacked Panes mode.",
        ]),
        new("0.14.0", "01 June 2026",
        [
            "Curve Analysis & Statistics now works in Compact Plot Surface mode. The Analysis Results panel, segments, and the shaded on-plot segment band — introduced for Stacked Panes in 0.13.0 — are now available on the Compact surface too. Open it from Curves > Analyze Curves… or View > Analysis Results Panel (Ctrl+R).",
            "Shift+drag on the Compact plot defines an analysis segment, with a live yellow preview band that follows your cursor as you drag. The committed band stretches across all curve bands.",
            "Right-click a Compact event line and choose \"Use as Segment Boundary\" — pick two lines to define a segment that tracks them as they move.",
            "Note: the Inline Metrics Overlay (corner labels) remains Stacked-only for now; Compact mode shows analysis in the side panel. Analysis for Grouped Parameter Plot mode is intentionally not included — per-curve statistics aren't a good fit for parametric grouped data.",
        ]),
        new("0.13.0", "01 June 2026",
        [
            "New: Curve Analysis & Statistics (Stacked Panes). The old fixed Min / Mean / Max box is replaced by a full Analysis Results panel — one row per visible curve, one column per metric, sortable and resizable. Open it from Curves > Analyze Curves… or View > Analysis Results Panel (Ctrl+R).",
            "18 metrics across three groups: Basic (Max, Min, Mean, Median, Range, Peak-to-Peak, Count, NaN Count), Dispersion (Std Dev, Variance, RMS, P5 / P50 / P95 percentiles), and Temporal (Slope with R² and a derived rate like ft/min or kt, Integral, First, Last). Default columns are Max / Min / Mean / Std Dev / Slope.",
            "Analysis segments: choose the X-range metrics are computed over. Visible window (tracks zoom/pan), Full data, Shift+drag to define a fixed range, or pick two event lines as a tracking boundary pair. The active segment is shaded on the plot. Manage Segments dialog renames, deletes, and activates segments; user segments persist in the .DPX project file.",
            "Point-on-curve metrics (Max / Min) have a ⊕ target button in each cell that flashes the exact (X, Y) on the plot.",
            "Curve units: an editable unit field in the Add Curves and Format Curve dialogs (auto-filled from \"Header (Unit)\" column names on import) drives the slope derived-rate labels. Units round-trip in the project file.",
            "Inline Metrics Overlay (View menu, Ctrl+I): draws the top metrics for each visible curve in its pane corner, so key numbers are visible without opening the side panel. Off by default.",
            "Copy the whole results table as TSV or Markdown for pasting into a spreadsheet or report.",
            "New keyboard shortcuts: Ctrl+R toggles the Analysis Results panel, Ctrl+I toggles the Inline Metrics overlay.",
            "Performance: pan/zoom recompute is debounced so a continuous drag triggers a single recompute on settle; the results table updates values in place instead of rebuilding when only the window shifts.",
            "Fixes from a review pass: Shift+drag no longer creates duplicate segments after a pane reloads; segment auto-numbering no longer collides with names restored from a saved project; an event-line-pair segment's stored range stays in sync when a non-active boundary line is moved; a leading missing-value (NaN) sample no longer breaks the full-data range.",
            "Internal: new mode-agnostic analysis engine (metric registry, units registry, AnalysisService, IAnalysisCurveSource / IAnalysisOverlayHost abstractions); legacy PlotPaneStatisticsManager / CurveStatisticsModel removed. Analysis in Compact and Grouped modes is scaffolded for a follow-up release.",
        ]),
        new("0.12.3", "17 May 2026",
        [
            "Title bar now shows an asterisk (e.g. \"* Stall.dpx - DatPlotX\") when the project has unsaved changes. The asterisk clears on Save.",
            "Stacked: right-clicking a major-axis intersection and choosing Add Text Annotation now centers the label on the click point (was offset down-right). Drag the label to fine-tune; right-click for Edit/Delete.",
            "Stacked: intersection callouts now stay inside the visible viewport when you Ctrl+Drag-zoom. Zoom back out and they return to their original positions.",
            "Stacked: Format Pane → Legend tab has a new Position dropdown — Hidden, Inside upper-left/right, Inside lower-left/right. Saved per pane in the project file.",
            "Stacked: fixed hover-tooltip dead-pane bug on newly added panes. Toggling Show Hover Tooltips no longer leaves any pane stuck without tooltips.",
            "Stacked: fixed a second-event-line case where the top pane's X-axis drifted out of sync until you panned.",
        ]),
        new("0.12.2", "17 May 2026",
        [
            "Fix: Stacked Panes mode now stacks tightly — the large vertical gap between panes (and above the top / below the bottom pane) is gone. Non-bottom panes no longer reserve room for the X-tick-label row they don't draw.",
        ]),
        new("0.12.1", "17 May 2026",
        [
            "Event lines now work the same way in Stacked Panes and Compact Plot Surface modes.",
            "Compact: adding an event line opens a dialog so you can name it and pick its color — no more silent E1/E2 auto-naming.",
            "Compact: every curve now gets a callout box with a black arrow leader at its intersection with the event line. Values show 4 decimals. Boxes are draggable; positions persist with the project file.",
            "Compact: callouts re-interpolate live while you drag the event line, so values and positions stay in sync.",
            "Stacked: right-click an event line for a \"Delete Event Line\" menu item — no more confirmation popup. Hit area is pixel-based so it stays usable at any zoom.",
            "Stacked: event-line labels now show on every pane (not just the bottom), in the line's color, anchored just inside the top of each pane.",
            "Stacked: the color you pick in the Add dialog is finally respected — lines and labels were always rendering orange.",
            "Stacked: dragging an event line moves it on every pane every frame, so the lines stay vertically aligned during the drag.",
            "Stacked: eliminated visible flicker while dragging an event line.",
            "Fix: stacked X-axis sync on the very first plot. Previously panes only aligned after you panned one of them; now they share the data range from the moment the first curve is plotted.",
        ]),
        new("0.12.0", "15 May 2026",
        [
            "New plot mode: Grouped Parameter Plot. A third project mode for tabular/array-style data where each row is one experimental point at a unique combination of discrete input values — parametric performance arrays, driftdown grids, climb-to-altitude charts, lookup tables. Mode is locked at project creation alongside Stacked Panes and Compact Plot Surface.",
            "Up to 8 columns can be marked as inputs. Each input becomes a sidebar dropdown of its distinct values plus an \"All\" choice; \"All\" expands that axis to one line per distinct value (cartesian product across All-mode inputs). Pick X and Y columns from the remaining non-input columns.",
            "Configure-Inputs wizard opens automatically on first import in a Grouped project and is re-openable via Tools → Configure Inputs… Per-input optional display label.",
            "Line cap: 48 lines drawn at once. Beyond cap, a warning bar shows \"Showing first 48 of N lines — narrow your selection.\" Columns with more than 5000 distinct values are flagged ineligible as input candidates (almost certainly continuous-value columns).",
            "Layout: 260px sidebar + GridSplitter + plot surface. Hover tooltip same as other panes. Source Data bottom pane stays available and collapsible; collapse state persists with the project. Top-bar X-Axis Parameter picker is hidden in Grouped mode (the sidebar owns X/Y selection).",
            "Image export via File → Export Image… (Ctrl+E) — PNG / JPEG / BMP.",
            "Fix: X/Y sidebar dropdowns no longer wipe out or duplicate when grouped inputs change or the X axis is reassigned.",
            "Import Options: Data start line auto-bumps when Header line or Unit line changes.",
            "Internal: 18 new tests pin the indexer projection logic, view-model rebuild semantics, and .DPX persistence round-trip (485 → 503 tests).",
        ]),
        new("0.11.2", "12 May 2026",
        [
            "Fix: loading a Stacked-mode project file no longer leaves an empty plot. Curves, event lines, callouts, and annotations now appear correctly on first open.",
            "Fix: annotations and event lines saved in a project now anchor against the real data range when the project is reloaded, instead of being pinned to a default ±10 range.",
            "Stacked mode: the global Add Curves / Manage Curves menu items and their keyboard shortcuts (Ctrl+Shift+A, Ctrl+M) are now disabled — they always targeted pane 0 or opened the wrong dialog. Right-click the pane you want to edit. Pressing the shortcut shows a one-line reminder in the status bar.",
            "Project load status now shows the file name instead of \"Untitled Project\".",
            "The application now starts maximized.",
            "Intersection-callout font size now matches event-line labels for visual parity.",
            "Internal: code-review remediation pass — restored the MVVM boundary between the file-operations service and the Import Options dialog, hardened curve-palette immutability, dialog-Escape handler lifetime, culture-fallback safety on import, and CSV log-throttling on bad data. 18 new unit tests pin the behaviors so they don't regress (471 → 485 tests).",
            "Internal: every remaining direct dialog construction in the main window code-behind now goes through the dialog service, finishing the M2 migration and making the workflows unit-testable.",
            "Performance: CSV row-fill uses fast-path TryParse for common types (double/int/long/DateTime/bool) so large imports do less allocation work on the hot path.",
            "Performance: the source-data grid preview caps at ~2M visible cells for very wide files (>200 columns), preventing an allocation storm on 5000-column imports.",
            "New: a static marketing website (DatPlotX.Website) lives in the repo for GitHub Pages / Cloudflare Pages hosting. Not a runtime dependency of the app.",
        ]),
        new("0.11.1", "11 May 2026",
        [
            "Internal: cleared three CA1000 build warnings around the file-operation result type. No user-visible change.",
        ]),
        new("0.11.0", "11 May 2026",
        [
            "Import Options redesigned: a two-column dialog now previews the first 100 lines of your file alongside the import controls, with role-tinted backgrounds so you can see exactly which lines DatPlotX treats as the header, units, data, or skipped prelude.",
            "Import Options: new line selectors for the header row, optional unit row, and first data row — no more guessing or pre-stripping metadata prelude rows. Set 0 to indicate no header or no unit row.",
            "Import Options: units detected on the unit line are now concatenated into the column name as \"Header (Unit)\", so axis labels and the source-data grid carry units automatically.",
            "Keyboard shortcuts greatly expanded across the main menu — Ctrl+Shift+E (Export Intersections), Ctrl+Q (Exit), Ctrl+Shift+A (Add Curves), Ctrl+M (Manage Curves), Ctrl+Shift+Delete (Clear All Curves), Ctrl+L (Add Event Line), Ctrl+Shift+L (Clear All Event Lines), Ctrl+F (Format Pane — Compact), Ctrl+, (Settings), Shift+F1 (What's New). One shortcut picks the Stacked or Compact variant automatically.",
            "Esc now closes any open dialog (Cancel) in both Stacked and Compact modes — including the confirmation prompts.",
            "Safety: Clear All Curves and Clear All Event Lines now ask before wiping, regardless of whether you trigger them from the menu, the keyboard shortcut, or the right-click menu. The prompt shows the count about to be removed.",
            "Default curve palette refreshed: pure green and pure cyan (which were hard to see on a white background) have been swapped for lime green and dodger blue. Existing projects keep their saved curve colors; only newly-added curves pick up the new defaults. Stacked and Compact modes now share one palette so colors can't drift between them.",
            "In-app User Guide (F1) rewritten: Stacked Panes and Compact Plot Surface now each have their own dedicated page with parallel structure, so you can compare them side-by-side and pick the right one for the job. Every menu, shortcut, and the new Import Options preview are documented.",
        ]),
        new("0.10.2", "11 May 2026",
        [
            "Stability: switching or reloading projects no longer carries stale event lines, callouts, or annotations from the previous project into the new one.",
            "Stability: removing a pane now releases its resources cleanly; long sessions with many add/remove cycles stay lighter on memory.",
            "Stability: loading the same project repeatedly no longer accumulates duplicate event subscriptions on its panes.",
            "Fix: Manage Curves now writes visibility from the dialog state instead of toggling, so applying the dialog repeatedly produces the same result.",
            "Fix: per-curve X-axis selection now persists when you save a project and is restored on reload.",
            "Fix: changing data files no longer leaves an out-of-date X-axis column selected when that column doesn't exist in the new data.",
            "Fix: load-from-path failures now surface as a clear error instead of being mis-reported as a user cancellation.",
            "Parser: CSV files with duplicate sanitized header names now get disambiguated suffixes instead of silently colliding.",
            "Parser: X-Plane data preprocessor now escapes fields containing commas, quotes, or newlines so the produced CSV is valid in every locale.",
            "Parser: huge CSV imports use less peak memory; X-Plane validates declared row count before reading the file body.",
            "Performance: compiled bindings re-enabled on the main window and the chip controls that the 0.10.1 sweep missed.",
            "Internal: completed the dialog-service migration for the main window — every dialog now goes through a single service interface, enabling broader unit-test coverage going forward.",
        ]),
        new("0.10.1", "10 May 2026",
        [
            "Performance: every dialog ported in 0.10.0 now uses compiled XAML bindings — faster startup, faster dialog opens, and binding mistakes get caught at build time instead of silently failing at runtime.",
            "Performance: the parameter filter in Add Curves (Stacked) no longer rebuilds the dropdown on every keystroke. Files with thousands of columns stay responsive while typing.",
            "Performance: the column filter in Add Compact Curves now hides rows directly from the data model instead of poking the visual tree, which fixes the case where typing in the filter before the list finished rendering would silently drop matches.",
            "Fix: long sessions no longer slowly leak event handlers from the chip-row and color-swatch widgets used across the redesigned dialogs.",
            "Fix: the wizard-stepper widget (used in Add Compact Curves) no longer risks a startup crash in unit-test / designer scenarios where theme resources aren't yet available.",
            "Internal: Format Pane (Stacked) was rewritten to live behind a dedicated view-model. No user-visible change, but the dialog is now testable without a live UI and follows the same MVVM pattern as the rest of the app.",
        ]),
        new("0.10.0", "10 May 2026",
        [
            "Redesign: every dialog and secondary window — Stacked and Compact, plus About / Help / What's New / Settings / Export — now shares the same window chrome, typography, and color tokens. The look is consistent regardless of which plot mode the project uses.",
            "Format Pane (Stacked) reorganized into per-axis tabs that match Format Compact Pane: Labels, Grid, X-Axis, Y1-Axis, Y2-Axis, Background, Legend. Each axis owns its own range, decimal places, and tick font controls.",
            "Add Curves (Stacked): a search box above the parameter list filters the dropdown live, so long parameter lists no longer require scrolling.",
            "Manage Curve (Compact): added a marker size slider, plus a Y-Axis section to set font size, bold, and decimal places per curve.",
            "Format Pane (Compact): added font size and bold controls for the X-axis label.",
            "Default font sizes lowered: pane title 24 → 20; axis labels, tick labels, legend, and statistics 18 → 14. Existing projects keep their saved values.",
            "Fix: Format Pane regressions introduced during the redesign — minor gridlines, legend font size, and statistics-box font/position now apply correctly without needing to pan the plot.",
            "Fix: arrow and text annotation dialogs no longer reject the chosen font size when opened.",
            "Fix: Manage Curve marker rows (Stacked + Compact) now correctly enable on first selection.",
        ]),
        new("0.9.1", "09 May 2026",
        [
            "Fix: switching plot modes or reloading a project no longer leaks the previous Compact surface's view-model graph (curves, hover handler, plot model). Long sessions stay lighter on memory.",
            "Performance: dragging an event line on the Compact Plot Surface is dramatically smoother on multi-curve / large datasets. Each pointer-move now updates the line in place instead of rebuilding the entire plot.",
            "Performance: faster startup and dialog opening — Add Compact Curves, Settings, User Guide, and What's New now use compiled XAML bindings instead of reflection.",
            "Stability: the startup Welcome view's Source Data pane collapse state now persists across save and reload of a project.",
        ]),
        new("0.9.0", "09 May 2026",
        [
            "New: event lines on the Compact Plot Surface. Right-click the plot to add an event line at the cursor X, drag a line to reposition it, right-click on a line to delete it, or use Clear All Event Lines. Event lines span every band top to bottom and persist when you save and reload a project.",
            "New: image export for the Compact Plot Surface. File > Export Image… (Ctrl+E) and the right-click Export Image… now both work in Compact mode — same PNG / JPEG / BMP / SVG choice and landscape / portrait dialog as Stacked.",
            "New: Export Image… on the Stacked-mode pane right-click menu, so both surfaces export from the same gesture. Exports all panes, the same as File > Export Image.",
            "UI: the top-level Event Lines menu no longer appears in Compact mode — Compact event lines are driven from the right-click menu instead.",
        ]),
        new("0.8.4", "08 May 2026",
        [
            "Fix: right-clicking the Compact Plot Surface no longer freezes mouse interaction on macOS. Pan, two-finger zoom, and the right-click menu all stay responsive after opening and closing the context menu.",
            "Fix: X-Plane data file detection now recognizes the same set of headers it did before 0.8.3.",
        ]),
        new("0.8.3", "08 May 2026",
        [
            "Workflow change: data import is now part of File > New Project (Ctrl+N). After picking the plot surface (Stacked Panes or Compact), the Open Data File dialog appears immediately — the plot only opens once you've chosen a CSV/TSV file. Cancelling at the file picker aborts the new project, so you no longer end up on an empty plot surface waiting for data.",
            "Removed: File > Import Data File… and its Ctrl+O shortcut. Use File > New Project (Ctrl+N) instead.",
            "Open Recent (File menu) shows only DatPlotX project (.DPX) files — no data-file (.csv) entries.",
        ]),
        new("0.8.2", "07 May 2026",
        [
            "Fix: hovering over the Compact Plot Surface no longer locks up the app on macOS. Tooltip behavior is unchanged — same snap-to-nearest-point, same Ctrl+T toggle.",
        ]),
        new("0.8.1", "07 May 2026",
        [
            "New: Curves > Manage Curve… (Compact mode) — pick a curve, then change its color, line style, marker style, marker color, or visibility; or delete it. Mirrors the Stacked-mode Format Curve dialog.",
            "New: hover tracker tooltip on the Compact Plot Surface — cursor over a curve shows the curve label and X / Y values at the cursor. Toggle with Tools > Show Hover Tooltips (Ctrl+T) — the same toggle that controls Stacked-mode tooltips.",
            "New: right-click context menu on the Compact Plot Surface — Add Curves, Manage Curve, Clear All Curves, Reset View, Format Pane, and Export Image, all in one place.",
            "New: per-curve Marker Color override on the Compact Plot Surface; falls back to the line color when not set. Saved with the project.",
            "Fix: right-clicking the Compact Plot Surface no longer freezes the app for several seconds.",
            "Fix: turning hover tooltips off (Ctrl+T) on the Compact Plot Surface now stays off — the tooltip used to pop back as soon as the cursor moved.",
            "Fix: app no longer crashes on launch or when opening the Manage Curve dialog.",
        ]),
        new("0.8.0", "07 May 2026",
        [
            "Compact Plot Surface: Y-axes now sit flush against the plot border instead of stair-stepping farther out with each added curve — matches the NTSB / FDM reference layout.",
            "Compact Plot Surface: rubber-band zoom is now Ctrl + left-drag, the same shortcut used in Stacked Panes mode.",
            "Compact Plot Surface: two-finger trackpad scroll on macOS now zooms the plot. Hover over the X-axis labels to zoom only X; hover over a band's Y axis to zoom only that band; hover over the plot interior to zoom both at the cursor.",
            "New: Tools > Format Pane… (Compact mode) — configure major/minor gridlines, X-axis label, decimal places, range, and plot background color. Settings are saved with the project.",
            "Help > User Guide: Plot Interaction table now documents Ctrl+drag rubber-band zoom, Ctrl+scroll fine zoom, and double-click / Home to reset.",
        ]),
        new("0.7.0", "06 May 2026",
        [
            "Project files now save with the .DPX extension (was .DPM). The legacy WPF DatPlot uses .DPM and the formats are not compatible — the new extension keeps file associations and double-click behavior unambiguous.",
        ]),
        new("0.6.0", "06 May 2026",
        [
            "New: Compact Plot Surface — single-area plot with one banded Y axis per parameter, alternating left/right. Matches FDA/FDM (NTSB exhibit) plot style for dense multi-parameter views.",
            "New: plot-style picker — when you start a new project or import data for the first time, you choose between the classic Stacked Panes layout and the new Compact Plot Surface. The choice is locked for the life of the project.",
            "New: Compact-mode 'Add Curves' dialog — pick the columns first, then configure axis side, color, line style, marker, boolean band, and overflow per curve.",
            "Boolean columns (0/1, true/false, on/off, yes/no) are auto-detected and get a smaller band so the plot doesn't waste vertical real estate on flag signals.",
            "Open Recent submenu under File for one-click access to recently opened projects.",
            "Loading a legacy .DPM file (saved before 0.6.0) prompts you to choose a plot style; the project is marked as modified so saving it captures the choice.",
        ]),
        new("0.5.2", "29 Apr 2026",
        [
            "Fixed crash when opening a saved project file (.DPM) — restoring panes and curves no longer races with the renderer",
            "New: hover a plotted point to see the X axis value and the curve's Y value at the cursor",
            "New: Tools menu — Ctrl+T toggles hover tooltips; Settings… persists the default state across sessions",
            "Fixed: marker colors are now saved to project files and restored on load",
            "Fixed: Save As no longer produces double .dpm.dpm extensions",
        ]),
        new("0.5.1", "28 Apr 2026",
        [
            "Code health: cleared all .NET analyzer warnings — build is now warning-free",
            "Numeric values (axis ticks, statistics, callouts, dialog text) now format consistently regardless of system locale",
            "Performance tune-ups across plot pane managers (TryGetValue lookups, concrete service types, faster List/string checks)",
            "PlotDataModel now properly disposes its underlying DataTable, reducing memory pressure on large imports",
        ]),
        new("0.5.0", "27 Apr 2026",
        [
            "Renamed application from DatPlot Modern to DatPlotX",
            "Help menu: new built-in User Guide (press F1) covering every menu, the right-click pane menu, and keyboard shortcuts",
            "Help menu: new What's New window for browsing release notes",
            "About dialog: version number now hides the embedded commit hash",
            "About dialog: copyright year updated to 2026",
            "Application version is now sourced from a single Directory.Build.props entry",
        ]),
    ];
}
